-- =====================================
-- generator=datazen
-- version=3.2.0
-- hash=76be46f41059c2b8ae46cccfa477949f
-- =====================================
expectedCVars = {}
expectedCVars["GamePadEnable"] = 1
expectedCVars["GamePadEmulateAlt"] = "PADPADDLE2"
expectedCVars["GamePadEmulateShift"] = "PADLSHOULDER"
expectedCVars["GamePadEmulateCtrl"] = "PADLTRIGGER"
expectedCVars["GamePadRunThreshold"] = 0
expectedCVars["GamePadCameraYawSpeed"] = 1.75
expectedCVars["AutoPushSpellToActionBar"] = 0
expectedCVars["advancedCombatLogging"] = 1
expectedCVars["autoLootDefault"] = 1
expectedCVars["autoLootRate"] = 50
expectedCVars["enableMultiActionBars"] = 15
expectedCVars["SoftTargetEnemy"] = 3
expectedCVars["SoftTargetFriend"] = 3
expectedCVars["SoftTargetInteract"] = 3
expectedCVars["SoftTargetIconFriend"] = 1
expectedCVars["SoftTargetNameplateInteract"] = 1
expectedCVars["floatingCombatTextCombatDamage"] = 0
expectedCVars["floatingCombatTextCombatHealing"] = 0
expectedCVars["cameraSmoothStyle"] = 1
expectedCVars["countdownForCooldowns"] = 1
expectedCVars["hideAdventureJournalAlerts"] = 1
expectedCVars["showTutorials"] = 0
expectedCVars["spellBookHidePassives"] = 1
expectedCVars["pvpFramesDisplayClassColor"] = 1
expectedCVars["pvpFramesDisplayPowerBars"] = 1
expectedCVars["raidFramesDisplayClassColor"] = 1
expectedCVars["raidFramesDisplayPowerBars"] = 1
expectedCVars["SoftTargetIconEnemy"] = 0
